### ISSUE TITLE
Unable to update bot commands

### ISSUE THREAD

**Issue by mctaylors** [TeamOctolings/Octobot#246]
### Description

Currently, if you add/remove a command, refresh the Discord (to update commands on the client side), the bot commands will not be updated (nor deleted or added)

### Expected vs. Actual Behavior

Expected: added/removed command(s)
Actual Behavior: *actually nothing happens*

### Reproduction Steps

1. open IDE and this project
2. add a brand new command
3. run Octobot
4. don't see the updated commands

### Other Information

Caused by https://github.com/LabsDevelopment/Octobot/commit/e01fde83c63a0eab0ae972b689395cbca4982d50

**Comment by Octol1ttle** [comment]
After investigating this issue I came to the conclusion that this is an issue on Discord's side. Code changes do not seem to affect whether the command tree gets updated or not (I got it to update a few times, but couldn't find any relation between my actions and the tree updating). The issue occurs before https://github.com/LabsDevelopment/Octobot/commit/e01fde83c63a0eab0ae972b689395cbca4982d50, so that theory is incorrect. What I tried is updating Remora.Discord and switching to the old way of registering commands.

**Comment by mctaylors** [comment]
> The issue occurs before https://github.com/TeamOctolings/Octobot/commit/e01fde83c63a0eab0ae972b689395cbca4982d50

I'm sorry, but I'm afraid you're mistaken. I was going to develop a new feature, but came back here.

The commands did not return until I reverted https://github.com/TeamOctolings/Octobot/commit/e01fde83c63a0eab0ae972b689395cbca4982d50. Yes, I waited a large amount of time, refreshed my Discord client multiple times, but it didn't help. This particular commit is the problem. I even reset the commands to make sure that my theory was correct.

I will try to figure out a possible solution to the problem shortly.
